version: '3.8'
services:
  api:
    build: ./server
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - PORT=3004
      - JWT_SECRET=dev_access_secret_change_me
      - JWT_REFRESH_SECRET=dev_refresh_secret_change_me
      - REDIS_URL=redis://redis:6300
      - DATABASE_URL=postgres://postgres:postgres@postgres:5400/dragon
      - CHUNK_SIZE=64
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:7-alpine
    ports:
      - "6300:6379"
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dragon
    ports:
      - "5400:5432"
  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
