name: CI
on:
  push:
    branches: [ main, master ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        working-directory: server
        run: npm ci
      - name: Type check
        working-directory: server
        run: npm run build --workspaces=false && echo OK
      - name: Lint placeholder
        working-directory: server
        run: npm run lint || true
